# -*- coding: utf-8 -*-
"""EY_NYTIMES

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hmB7RHWzEEtGfoetfIzI-ml5gqf3em-F
"""

import requests,json

response = requests.get('http://api.nytimes.com/svc/semantic/v2/concept/name/nytd_geo/China.json?fields=all&api-key=Gy4FiuBTFZlOJ3YRYh4Zn5L0UvLUccTG')

files = response.json()
print(files)